//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgtMerkezi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EgtMerkezi.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız Soyadınız.
        /// </summary>
        public static string AdSoyad {
            get {
                return ResourceManager.GetString("AdSoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string AnaSayfa {
            get {
                return ResourceManager.GetString("AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitede arama....
        /// </summary>
        public static string Arama {
            get {
                return ResourceManager.GetString("Arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvur.
        /// </summary>
        public static string Basvur {
            get {
                return ResourceManager.GetString("Basvur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi İstek Formu.
        /// </summary>
        public static string BilgiIstekFormu {
            get {
                return ResourceManager.GetString("BilgiIstekFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dökümanlar.
        /// </summary>
        public static string Dokumanlar {
            get {
                return ResourceManager.GetString("Dokumanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUYURULAR / HABERLER.
        /// </summary>
        public static string Duyurular {
            get {
                return ResourceManager.GetString("Duyurular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EĞİTİM MERKEZİ.
        /// </summary>
        public static string EgitimMerkezi {
            get {
                return ResourceManager.GetString("EgitimMerkezi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta Adresiniz.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurslar.
        /// </summary>
        public static string Kurslar {
            get {
                return ResourceManager.GetString("Kurslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞRENCİ GÖRÜŞLERİ.
        /// </summary>
        public static string OgrenciGorusleri {
            get {
                return ResourceManager.GetString("OgrenciGorusleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya Üniversitesi.
        /// </summary>
        public static string Sau {
            get {
                return ResourceManager.GetString("Sau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Seçiniz --.
        /// </summary>
        public static string Seciniz {
            get {
                return ResourceManager.GetString("Seciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sınav Notları.
        /// </summary>
        public static string SınavNotlari {
            get {
                return ResourceManager.GetString("SınavNotlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Özel.
        /// </summary>
        public static string SizeOzel {
            get {
                return ResourceManager.GetString("SizeOzel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TANITIM VİDEOSU.
        /// </summary>
        public static string TanıtımVideosu {
            get {
                return ResourceManager.GetString("TanıtımVideosu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercih Edilen Eğitimler.
        /// </summary>
        public static string TercihEdilenEgitimler {
            get {
                return ResourceManager.GetString("TercihEdilenEgitimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Girişi.
        /// </summary>
        public static string UyeGiris {
            get {
                return ResourceManager.GetString("UyeGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
    }
}
