//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgtMerkezi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EgitimMerkeziEntities : DbContext
    {
        public EgitimMerkeziEntities()
            : base("name=EgitimMerkeziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bilgilendirme> Bilgilendirme { get; set; }
        public virtual DbSet<Duyurular> Duyurular { get; set; }
        public virtual DbSet<Kurs> Kurs { get; set; }
        public virtual DbSet<KursOgrenci> KursOgrenci { get; set; }
        public virtual DbSet<KursTip> KursTip { get; set; }
        public virtual DbSet<OgrenciGorus> OgrenciGorus { get; set; }
        public virtual DbSet<OgretimElemani> OgretimElemani { get; set; }
        public virtual DbSet<Oneri> Oneri { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
    }
}
