//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgtMerkezi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretimElemani
    {
        public OgretimElemani()
        {
            this.Kurs = new HashSet<Kurs>();
        }
    
        public int OgretimElemanId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public string Eposta { get; set; }
        public string Ozgecmis { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual ICollection<Kurs> Kurs { get; set; }
    }
}
