//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgtMerkezi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciGorus
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public byte[] Foto { get; set; }
        public string Gorus { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
